server:
  error:
    include-message: always

spring:
  mvc:
    log-resolved-exception: true
    log-request-details: true
  datasource:
    url: jdbc:postgresql://localhost:5433/customer
    username: amigoscode
    password: password
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


logging:
  level:
    root: INFO